repos:
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 24.4.2
   hooks:
     - id: black-conda
       args:
         - --safe
         - --target-version=py38
       exclude: changeforest_simulations/methods/multirank/
 - repo: https://github.com/Quantco/pre-commit-mirrors-isort
   rev: '5.13.2'
   hooks:
    - id: isort-conda
      additional_dependencies: [toml]
      exclude: changeforest_simulations/methods/multirank/
 - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
   rev: 7.1.1
   hooks:
    - id: flake8-conda