name: ivmodels-simulations
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.7
  - numpy
  - scipy
  - pytest  # tests only
  - scikit-learn
  - glum
  - pandas  # optional
  - click
  - h5py
  - matplotlib