name: ivmodels-simulations
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.7
  - numpy
  - ivmodels>=0.5.0
  - scipy
  - scikit-learn
  - glum
  - pandas
  - click
  - h5py
  - matplotlib